### ISSUE TITLE
[BUG] fly by shield!

### ISSUE THREAD

**Issue by UnknownNull** [WaterdogPE/WaterdogPE#243]
**Describe the bug**
If the server is without a proxy, this problem does not exist, but if waterdogpe is used, this problem occurs.

Hold the shield and sit down, then jump, you will go into the air, and if you sit down again, the flight will be cancelled. (Try it yourself to find out)
**To Reproduce**
1. Join server
2. Type command XYZ
3. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/91208232/201448066-07801bc8-99d2-4b96-8353-ea7e15b3d520.png)
**Platform Information:**
 - Game Platform: ios, android, win
 - Game (Client) Version 1.19 and 1.19.10 and 1.19.20 and..
 - Server OS win  pmmp server
 - Java Version Java 18 
 - Server Deployment Method [e.g. Pterodactyl, Docker]

**Additional context**

**Comment by DavyCraft648** [comment]
https://github.com/WaterdogPE/WaterdogPE/issues/123#issuecomment-950294886

**Comment by UnknownNull** [comment]
> [#123 (comment)](https://github.com/WaterdogPE/WaterdogPE/issues/123#issuecomment-950294886)

The one I reported is for pmmp and this solution was written for nukkit

**Comment by DavyCraft648** [comment]
> When sending FLAGS2, you should sent FLAGS1 as well.

the solution is the same
it should be like this https://gist.github.com/DavyCraft648/09bb99225dc0e4140d9bedea91b50b1f

**Comment by UnknownNull** [comment]
> > When sending FLAGS2, you should sent FLAGS1 as well.
> 
> the solution is the same it should be like this https://gist.github.com/DavyCraft648/09bb99225dc0e4140d9bedea91b50b1f

LOL. this is multi bugs

https://user-images.githubusercontent.com/91208232/201496075-81344d8d-6110-44de-b643-3c107b33dee1.mp4

**Comment by DavyCraft648** [comment]
then fix it

**Comment by UnknownNull** [comment]
Before using this plugin, the shield would rise and the attacker would be thrown back, but with the use of this plugin, the shield does not rise and the person who gets hit is thrown forward.

> then fix that I don't think your _multi bugs_ is related to this issue

**Comment by TobiasGrether** [comment]
What version of PocketMine/Nukkit are you running? And also, what version of WDPE are you using? (Commit hashes or release versions please)

**Comment by UnknownNull** [comment]
> What version of PocketMine/Nukkit are you running? And also, what version of WDPE are you using? (Commit hashes or release versions please)

pmmp 4.5.1
wdpe 1.1.8

**Comment by Alemiz112** [comment]
This should be fixed now.

**Comment by UnknownNull** [comment]
> This should be fixed now.

not fixed
![shield](https://github.com/WaterdogPE/WaterdogPE/assets/91208232/d16304dd-fdc6-4667-b1d1-5c2eb3bd7834)
